<pubmed>
<PMID>
{data(//MedlineCitation/PMID)}
</PMID>
<date>
{data(//MedlineCitation/DateCompleted/Year)}
</date>
<title>
{data(//MedlineCitation/Article/ArticleTitle)}
</title>
<journal>
{data(//MedlineCitation/Article/Journal/Title)}
</journal>
<author>
{data(//AuthorList/Author[1]/LastName)}
</author>
<abstract>
{data(//AbstractText)}
</abstract>
</pubmed>